name: EcoVote
main: jp.minecraftuser.ecovote.EcoVote
version: ${project.version}
api-version: 1.15
depend: [EcoFramework, Votifier]
softdepend: [EcoUserManager, EcoMQTTServerLog]
commands:
  evote:
    description: evote command root
    usage: /evote
    permission: ecovote
  evote get:
    description: Get the stored voting gifts. 
    usage: /evote get
    permission: ecovote.get
  evote test:
    description: test evote plugin
    usage: /evote test
    permission: ecovote.test
  evote reload:
    description: reload config.yml
    usage: /evote reload
    permission: ecovote.reload
    

